vim.keymap.set('n', '<M-h>', ':lua require("harpoon.ui").toggle_quick_menu()<CR>', { noremap = true, silent = true })
vim.keymap.set('n', '<M-a>', ':lua require("harpoon.mark").add_file()<CR>', { noremap = true, silent = true })
vim.keymap.set('n', '<M-l>', ':lua require("harpoon.ui").nav_next()<CR>', { noremap = true, silent = true })
vim.keymap.set('n', '<M-L>', ':lua require("harpoon.ui").nav_prev()<CR>', { noremap = true, silent = true })
vim.keymap.set('n', '<M-r>', ':lua require("harpoon.mark").rm_file()<CR>', { noremap = true, silent = true })
